name: user_directory
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.17.12
  build_runner: ^2.0.4

flutter:

  uses-material-design: true
