name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.2.2'

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test
